/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'k_watanabe' at '17/02/14 18:38' with Gradle 3.1
 *
 * @author k_watanabe, @date 17/02/14 18:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
