import java.io.File;
import org.eclipse.jgit.storage.file.FileRepositoryBuilder;
import org.eclipse.jgit.lib.Repository;
import org.eclipse.jgit.lib.Ref;
import org.eclipse.jgit.lib.ObjectId;
import org.eclipse.jgit.lib.ObjectLoader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        Repository repo = new FileRepositoryBuilder()
            .setGitDir(new File("C:\\repositories\\repositories-github\\omotenashi\\.git"))
            .build();

        // 参照を取得する
        Ref master = repo.getRefDatabase().findRef("master");

        // 参照の指すオブジェクトを取得する
        ObjectId masterTip = master.getObjectId();

        // Rev-parse文法を使う
        ObjectId obj = repo.resolve("HEAD^{tree}");

        // オブジェクトの生の内容をロードする
        ObjectLoader loader = repo.open(masterTip);
        loader.copyTo(System.out);
    }
}
