/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tools.launcher;

import java.io.IOException;
import java.io.File;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() throws IOException, InterruptedException {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        
        
        Runtime runtime = Runtime.getRuntime();
//        Process process = runtime.exec(new String[]{"cmd", "個人 - Chrome.lnk"}, new String[]{}, new File("C:\\User\\k-watanabe\\Documents\\@\\個人"));
        Process process = runtime.exec(new String[]{"cmd", "電卓.lnk"}, new String[]{}, new File("C:\\User\\k-watanabe\\Documents\\@\\App-util"));
        process.waitFor();
    }
}
