/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jsonwatcher;

import java.util.Arrays;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	String[] files = args;

    	if (files.length == 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Json File", "json", "jsn");
            chooser.setFileFilter(filter);
            int returnVal = chooser.showOpenDialog(null);
            if(returnVal != JFileChooser.APPROVE_OPTION) {
                return ;
                }

            files = new String[] {chooser.getSelectedFile().getName()};
        }

    	Arrays.asList(files).stream().forEach(v -> {
    		JsonWatcherFrame f = new JsonWatcherFrame(v);
    		f.setVisible(true);
    	});
    	
    }
}
