package tools.dbconnector7;

import tools.dbconnector7.logic.DatabaseLogic;
import tools.dbconnector7.persistence.PersistenceManager;
import tools.dbconnector7.ui.MainFrame;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	private AppHandle appHandle;
    private MainFrame mainFrame;

    private void launch() {
    	appHandle = new AppHandle();

    	appHandle.setPersistenceManager(new PersistenceManager());
    	appHandle.setDatabaseLogic(new DatabaseLogic(appHandle));

    	mainFrame = new MainFrame(appHandle);
        mainFrame.setVisible(true);
    }

    public static void main(String[] args) {
        App app = new App();
        app.launch();
    }
}
