package tools.dbconnector7;

import tools.dbconnector7.ui.MainFrame;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private MainFrame mainFrame;

    private void launch() {
        mainFrame = new MainFrame();
        mainFrame.show();
    }

    public static void main(String[] args) {
        App app = new App();
        app.launch();
    }
}
