/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nave' at '17/01/05 0:21' with Gradle 2.3
 *
 * @author nave, @date 17/01/05 0:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
