/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nave' at '17/04/27 0:29' with Gradle 2.3
 *
 * @author nave, @date 17/04/27 0:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
