/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package analogclock;

class AppTest {

	/*
	@Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    */
}
